### ISSUE TITLE
Which Version of TensorFlow and Transformers is used in this code?

### ISSUE THREAD

**Issue by PiyushKyushu** [RaviTejaMaddhini/Analytics-Vidya-Sentiment-Analysis-Hackathon#2]
Hi Ravi,
Can you tell me which version of TensorFlow and transformers you used? Because I am running with some errors because of different versions of these.
I possible please tell the version of other dependencies also.

Thanks.

**Comment by RaviTejaMaddhini** [comment]
Piyush, I may not be able to provide exact versions (as I have deleted that vm) but I have used tensorflow (>2.1.0) and the latest transformers package.

**Comment by PiyushKyushu** [comment]
Thank you for your response.
