### ISSUE TITLE
OSError: Unable to open file (unable to open file: name = 'robert/models/checkpoint-baseline-0.9480.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

### ISSUE THREAD

**Issue by PiyushKyushu** [RaviTejaMaddhini/Analytics-Vidya-Sentiment-Analysis-Hackathon#3]
Hi Ravi,

When I run the below line of code. 

`model.load_weights("robert/models/checkpoint-baseline-0.9480.h5")`

I encountered 

> OSError: Unable to open file (unable to open file: name = 'robert/models/checkpoint-baseline-0.9480.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

Can you please explain to me what is the issue and how can I solve it? I tried to read and follow stackoverflow answers also but couldn't solve the problem.

Thank you.

**Comment by RaviTejaMaddhini** [comment]
Piyush, 
            In the above line, I am trying to load one of the model checkpoint, which was available at "robert/models/" directory. You need to remove that line  as you don't have that in your system.

**Comment by PiyushKyushu** [comment]
Thanks a lot. 
I solve the issue by removing the line as you mentioned.
